<?php
$this->load->view('admin/menu_tab');
$this->load->view('admin/menu_tab2');
$this->load->view('admin/menu_tab3');
$this->load->view('admin/menu_tab4');
$this->load->view('admin/menu_tab5');
$this->load->view('admin/menu_tab6');
$this->load->view('admin/menu_tab7');
$this->load->view('admin/menu_tab8');
?>